"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ACCOUNTS_USER_TABLE = exports.ACCOUNTS_TABLE = exports.LOGS_TABLE = exports.CATEGORY_TABLE = exports.USER_TABLE = exports.CDR_ANALYTICS_TABLE = exports.CDR_LOGS_TABLE = exports.API_USERS_TABLE = void 0;
exports.API_USERS_TABLE = "users_api";
exports.CDR_LOGS_TABLE = "cdr_logs";
exports.CDR_ANALYTICS_TABLE = "cdr_analytics ";
exports.USER_TABLE = "users";
exports.CATEGORY_TABLE = "categories";
exports.LOGS_TABLE = "logs";
exports.ACCOUNTS_TABLE = "accounts";
exports.ACCOUNTS_USER_TABLE = "accounts_users";
